In [2]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib import font_manager as fm
from matplotlib import rc
import platform

In [3]:
font_location = 'C:/Users/yeonn/AppData/Local/Microsoft/Windows/Fonts/D2Coding-Ver1.3.2-20180524-all.ttc' 
font_name = fm.FontProperties(fname=font_location).get_name()
plt.rc('font', family=font_name)

In [4]:
df=pd.read_csv('final_2.csv')
df2=pd.read_csv('keward.csv')

In [5]:
df2 = df2.rename(columns={'keward': '지역명'})

In [6]:
non_matching=['주안동','갈산동','학익동','구월동','계양동','계산동','간석동','만수동',
             '가좌동','송도동','작전동','논현동','동춘동','도화동','송림동','가정동',
             '청라동','용현동','송현동','청천동','효성동','연수동','숭의동','석남동',
             '옥련동','화수동','십정동']
change_list=['주안1동','주안2동', '주안3동','주안4동', '주안5동', '주안6동', '주안7동', '주안8동',
            '갈산1동', '갈산2동','학익1동', '학익2동','구월1동', '구월2동', '구월3동', '구월4동',
            '계양1동', '계양2동', '계양3동','계산1동', '계산2동', '계산3동', '계산4동','간석1동',
            '간석2동', '간석3동', '간석4동','만수1동','만수2동', '만수3동', '만수4동', '만수5동', '만수6동',
             '가좌1동', '가좌2동', '가좌3동', '가좌4동','송도1동', '송도2동', '송도3동', '송도4동', '송도5동',
             '작전1동', '작전2동','논현1동', '논현2동','동춘1동', '동춘2동', '동춘3동','도화1동','도화2,3동',
             '송림1동', '송림2동', '송림3,5동','송림4동', '송림6동','가정1동', '가정2동', '가정3동','청라1동',
            '청라2동', '청라3동','용현1,4동', '용현2동', '용현3동', '용현5동','송현1,2동', '송현3동',
             '청천1동', '청천2동','효성1동', '효성2동', '연수1동','연수2동', '연수3동','숭의1,3동', '숭의2동',
             '숭의4동','석남1동', '석남2동', '석남3동','옥련1동', '옥련2동','화수2동','십정1동', '십정2동'
            ]

df['지역명'].unique()

array(['가정1동', '가정2동', '가정3동', '가좌1동', '가좌2동', '가좌3동', '가좌4동', '간석1동',
       '간석2동', '간석3동', '간석4동', '갈산1동', '갈산2동', '강화읍', '개항동', '검단동',
       '검암경서동', '계산1동', '계산2동', '계산3동', '계산4동', '계양1동', '계양2동', '계양3동',
       '관교동', '교동면', '구월1동', '구월2동', '구월3동', '구월4동', '금창동', '길상면',
       '남촌도림동', '내가면', '논현1동', '논현2동', '논현고잔동', '당하동', '도원동', '도화1동',
       '도화2,3동', '동인천동', '동춘1동', '동춘2동', '동춘3동', '마전동', '만석동', '만수1동',
       '만수2동', '만수3동', '만수4동', '만수5동', '만수6동', '문학동', '백령면', '부개1동',
       '부개2동', '부개3동', '부평1동', '부평2동', '부평3동', '부평4동', '부평5동', '부평6동',
       '북도면', '불로대곡동', '불은면', '산곡1동', '산곡2동', '산곡3동', '산곡4동', '삼산1동',
       '삼산2동', '삼산면', '서창2동', '석남1동', '석남2동', '석남3동', '선원면', '선학동',
       '송도1동', '송도2동', '송도3동', '송도4동', '송도5동', '송림1동', '송림2동', '송림3,5동',
       '송림4동', '송림6동', '송해면', '송현1,2동', '송현3동', '숭의1,3동', '숭의2동', '숭의4동',
       '신포동', '신현원창동', '신흥동', '십정1동', '십정2동', '아라동', '양도면', '양사면', '연수1동',
       '연수2동', '연수3동', '연안동', '연희동', '영종1동', '영종동', '영흥면', '오류왕길동',
       '옥련1동', '옥련2동', '용유동', '용현1,4동', '용현2동', '용현3동', '용현5동', '운서동',
       '원당동', '율목동', '일신동', '작전1동', '작전2동', '작전서운동', '장수서창동', '주안1동',
       '주안2동', '주안3동', '주안4동', '주안5동', '주안6동', '주안7동', '주안8동', '청라1동',
       '청라2동', '청라3동', '청천1동', '청천2동', '청학동', '하점면', '학익1동', '학익2동',
       '화도면', '화수1,화평동', '화수2동', '효성1동', '효성2동'], dtype=object)

In [7]:
juan_dong1 = df2[df2['지역명'] == '주안동'].copy()
juan_dong1['지역명']='주안1동'
df2 = pd.concat([df2, juan_dong1], ignore_index=True)

juan_dong2 = df2[df2['지역명'] == '주안동'].copy()
juan_dong2['지역명']='주안2동'
df2 = pd.concat([df2, juan_dong2], ignore_index=True)

juan_dong3 = df2[df2['지역명'] == '주안동'].copy()
juan_dong3['지역명']='주안3동'
df2 = pd.concat([df2, juan_dong3], ignore_index=True)

juan_dong4 = df2[df2['지역명'] == '주안동'].copy()
juan_dong4['지역명']='주안4동'
df2 = pd.concat([df2, juan_dong4], ignore_index=True)

juan_dong5 = df2[df2['지역명'] == '주안동'].copy()
juan_dong5['지역명']='주안5동'
df2 = pd.concat([df2, juan_dong5], ignore_index=True)

juan_dong6 = df2[df2['지역명'] == '주안동'].copy()
juan_dong6['지역명']='주안6동'
df2 = pd.concat([df2, juan_dong6], ignore_index=True)

juan_dong7 = df2[df2['지역명'] == '주안동'].copy()
juan_dong7['지역명']='주안7동'
df2 = pd.concat([df2, juan_dong7], ignore_index=True)

juan_dong8 = df2[df2['지역명'] == '주안동'].copy()
juan_dong8['지역명']='주안8동'
df2 = pd.concat([df2, juan_dong8], ignore_index=True)

galsan1 = df2[df2['지역명'] == '갈산동'].copy()
galsan1['지역명']='갈산1동'
df2 = pd.concat([df2, galsan1], ignore_index=True)

galsan2 = df2[df2['지역명'] == '갈산동'].copy()
galsan2['지역명']='갈산2동'
df2 = pd.concat([df2, galsan2], ignore_index=True)

hakik1 = df2[df2['지역명'] == '학익동'].copy()
hakik1['지역명']='학익1동'
df2 = pd.concat([df2, hakik1], ignore_index=True)

hakik2 = df2[df2['지역명'] == '학익동'].copy()
hakik2['지역명']='학익2동'
df2 = pd.concat([df2, hakik2], ignore_index=True)

guwal1 = df2[df2['지역명'] == '구월동'].copy()
guwal1['지역명']='구월1동'
df2 = pd.concat([df2, guwal1], ignore_index=True)

guwal2 = df2[df2['지역명'] == '구월동'].copy()
guwal2['지역명']='구월2동'
df2 = pd.concat([df2, guwal2], ignore_index=True)

guwal3 = df2[df2['지역명'] == '구월동'].copy()
guwal3['지역명']='구월3동'
df2 = pd.concat([df2, guwal3], ignore_index=True)

guwal4 = df2[df2['지역명'] == '구월동'].copy()
guwal4['지역명']='구월4동'
df2 = pd.concat([df2, guwal4], ignore_index=True)

geyang1 = df2[df2['지역명'] == '계양동'].copy()
geyang1['지역명']='계양1동'
df2 = pd.concat([df2, geyang1], ignore_index=True)

geyang2 = df2[df2['지역명'] == '계양동'].copy()
geyang2['지역명']='계양2동'
df2 = pd.concat([df2, geyang2], ignore_index=True)

geyang3 = df2[df2['지역명'] == '계양동'].copy()
geyang3['지역명']='계양3동'
df2 = pd.concat([df2, geyang3], ignore_index=True)

gesang1 = df2[df2['지역명'] == '계산동'].copy()
gesang1['지역명']='계산1동'
df2 = pd.concat([df2, gesang1], ignore_index=True)

gesang2 = df2[df2['지역명'] == '계산동'].copy()
gesang2['지역명']='계산2동'
df2 = pd.concat([df2, gesang2], ignore_index=True)

gesang3 = df2[df2['지역명'] == '계산동'].copy()
gesang3['지역명']='계산3동'
df2 = pd.concat([df2, gesang3], ignore_index=True)

gesang4 = df2[df2['지역명'] == '계산동'].copy()
gesang4['지역명']='계산4동'
df2 = pd.concat([df2, gesang4], ignore_index=True)

gansang1 = df2[df2['지역명'] == '간석동'].copy()
gansang1['지역명']='간석1동'
df2 = pd.concat([df2, gansang1], ignore_index=True)

gansang2 = df2[df2['지역명'] == '간석동'].copy()
gansang2['지역명']='간석2동'
df2 = pd.concat([df2, gansang2], ignore_index=True)

gansang3 = df2[df2['지역명'] == '간석동'].copy()
gansang3['지역명']='간석3동'
df2 = pd.concat([df2, gansang3], ignore_index=True)

gansang4 = df2[df2['지역명'] == '간석동'].copy()
gansang4['지역명']='간석4동'
df2 = pd.concat([df2, gansang4], ignore_index=True)

mansu1 = df2[df2['지역명'] == '만수동'].copy()
mansu1['지역명']='만수1동'
df2 = pd.concat([df2, mansu1], ignore_index=True)

mansu2 = df2[df2['지역명'] == '만수동'].copy()
mansu2['지역명']='만수2동'
df2 = pd.concat([df2, mansu2], ignore_index=True)

mansu3 = df2[df2['지역명'] == '만수동'].copy()
mansu3['지역명']='만수3동'
df2 = pd.concat([df2, mansu3], ignore_index=True)

mansu4 = df2[df2['지역명'] == '만수동'].copy()
mansu4['지역명']='만수4동'
df2 = pd.concat([df2, mansu4], ignore_index=True)

mansu5 = df2[df2['지역명'] == '만수동'].copy()
mansu5['지역명']='만수5동'
df2 = pd.concat([df2, mansu5], ignore_index=True)

mansu6 = df2[df2['지역명'] == '만수동'].copy()
mansu6['지역명']='만수6동'
df2 = pd.concat([df2, mansu6], ignore_index=True)

gazua1 = df2[df2['지역명'] == '가좌동'].copy()
gazua1['지역명']='가좌1동'
df2 = pd.concat([df2, gazua1], ignore_index=True)

gazua1 = df2[df2['지역명'] == '가좌동'].copy()
gazua1['지역명']='가좌1동'
df2 = pd.concat([df2, gazua1], ignore_index=True)

gazua2 = df2[df2['지역명'] == '가좌동'].copy()
gazua2['지역명']='가좌2동'
df2 = pd.concat([df2, gazua2], ignore_index=True)

gazua3 = df2[df2['지역명'] == '가좌동'].copy()
gazua3['지역명']='가좌3동'
df2 = pd.concat([df2, gazua3], ignore_index=True)

gazua4 = df2[df2['지역명'] == '가좌동'].copy()
gazua4['지역명']='가좌4동'
df2 = pd.concat([df2, gazua4], ignore_index=True)

In [8]:
songdo1 = df2[df2['지역명'] == '송도동'].copy()
songdo1['지역명']='송도1동'
df2 = pd.concat([df2, songdo1], ignore_index=True)

songdo2 = df2[df2['지역명'] == '송도동'].copy()
songdo2['지역명']='송도2동'
df2 = pd.concat([df2, songdo2], ignore_index=True)

songdo3 = df2[df2['지역명'] == '송도동'].copy()
songdo3['지역명']='송도3동'
df2 = pd.concat([df2, songdo3], ignore_index=True)

songdo4 = df2[df2['지역명'] == '송도동'].copy()
songdo4['지역명']='송도4동'
df2 = pd.concat([df2, songdo4], ignore_index=True)

songdo5 = df2[df2['지역명'] == '송도동'].copy()
songdo5['지역명']='송도5동'
df2 = pd.concat([df2, songdo5], ignore_index=True)

jackjun1 = df2[df2['지역명'] == '작전동'].copy()
jackjun1['지역명']='작전1동'
df2 = pd.concat([df2, jackjun1], ignore_index=True)

jackjun2 = df2[df2['지역명'] == '작전동'].copy()
jackjun2['지역명']='작전2동'
df2 = pd.concat([df2, jackjun2], ignore_index=True)

nonhuen1 = df2[df2['지역명'] == '논현동'].copy()
nonhuen1['지역명']='논현1동'
df2 = pd.concat([df2, nonhuen1], ignore_index=True)

nonhuen2 = df2[df2['지역명'] == '논현동'].copy()
nonhuen2['지역명']='논현2동'
df2 = pd.concat([df2, nonhuen2], ignore_index=True)

nonhuen2 = df2[df2['지역명'] == '논현동'].copy()
nonhuen2['지역명']='논현2동'
df2 = pd.concat([df2, nonhuen2], ignore_index=True)

dongchun1 = df2[df2['지역명'] == '동춘동'].copy()
dongchun1['지역명']='동춘1동'
df2 = pd.concat([df2, dongchun1], ignore_index=True)

dongchun2 = df2[df2['지역명'] == '동춘동'].copy()
dongchun2['지역명']='동춘2동'
df2 = pd.concat([df2, dongchun2], ignore_index=True)

dongchun3 = df2[df2['지역명'] == '동춘동'].copy()
dongchun3['지역명']='동춘3동'
df2 = pd.concat([df2, dongchun3], ignore_index=True)

dongchun3 = df2[df2['지역명'] == '동춘동'].copy()
dongchun3['지역명']='동춘3동'
df2 = pd.concat([df2, dongchun3], ignore_index=True)

doha1 = df2[df2['지역명'] == '도화동'].copy()
doha1['지역명']='도화1동'
df2 = pd.concat([df2, doha1], ignore_index=True)

doha23 = df2[df2['지역명'] == '도화동'].copy()
doha23['지역명']='도화2,3동'
df2 = pd.concat([df2, doha23], ignore_index=True)

songlim1 = df2[df2['지역명'] == '송림동'].copy()
songlim1['지역명']='송림1동'
df2 = pd.concat([df2, songlim1], ignore_index=True)

songlim2 = df2[df2['지역명'] == '송림동'].copy()
songlim2['지역명']='송림2동'
df2 = pd.concat([df2, songlim2], ignore_index=True)

songlim35 = df2[df2['지역명'] == '송림동'].copy()
songlim35['지역명']='송림3,5동'
df2 = pd.concat([df2, songlim35], ignore_index=True)

songlim4 = df2[df2['지역명'] == '송림동'].copy()
songlim4['지역명']='송림4동'
df2 = pd.concat([df2, songlim4], ignore_index=True)

songlim6 = df2[df2['지역명'] == '송림동'].copy()
songlim6['지역명']='송림6동'
df2 = pd.concat([df2, songlim6], ignore_index=True)

jajung1 = df2[df2['지역명'] == '가정동'].copy()
jajung1['지역명']='가정1동'
df2 = pd.concat([df2, jajung1], ignore_index=True)

jajung2 = df2[df2['지역명'] == '가정동'].copy()
jajung2['지역명']='가정2동'
df2 = pd.concat([df2, jajung2], ignore_index=True)

jajung3 = df2[df2['지역명'] == '가정동'].copy()
jajung3['지역명']='가정3동'
df2 = pd.concat([df2, jajung3], ignore_index=True)

chungra1 = df2[df2['지역명'] == '청라동'].copy()
chungra1['지역명']='청라1동'
df2 = pd.concat([df2, chungra1], ignore_index=True)

chungra2 = df2[df2['지역명'] == '청라동'].copy()
chungra2['지역명']='청라2동'
df2 = pd.concat([df2, chungra2], ignore_index=True)

chungra3 = df2[df2['지역명'] == '청라동'].copy()
chungra3['지역명']='청라3동'
df2 = pd.concat([df2, chungra3], ignore_index=True)

yonghun14 = df2[df2['지역명'] == '용현동'].copy()
yonghun14['지역명']='용현1,4동'
df2 = pd.concat([df2, yonghun14], ignore_index=True)

yonghun2 = df2[df2['지역명'] == '용현동'].copy()
yonghun2['지역명']='용현2동'
df2 = pd.concat([df2, yonghun2], ignore_index=True)

yonghun3 = df2[df2['지역명'] == '용현동'].copy()
yonghun3['지역명']='용현3동'
df2 = pd.concat([df2, yonghun3], ignore_index=True)

yonghun5 = df2[df2['지역명'] == '용현동'].copy()
yonghun5['지역명']='용현5동'
df2 = pd.concat([df2, yonghun5], ignore_index=True)

yonghun5 = df2[df2['지역명'] == '용현동'].copy()
yonghun5['지역명']='용현5동'
df2 = pd.concat([df2, yonghun5], ignore_index=True)

songhun1 = df2[df2['지역명'] == '송현동'].copy()
songhun1['지역명']='송현1,2동'
df2 = pd.concat([df2, songhun1], ignore_index=True)

songhun3 = df2[df2['지역명'] == '송현동'].copy()
songhun3['지역명']='송현3동'
df2 = pd.concat([df2, songhun3], ignore_index=True)

chungchun1 = df2[df2['지역명'] == '청천동'].copy()
chungchun1['지역명']='청천1동'
df2 = pd.concat([df2, chungchun1], ignore_index=True)

chungchun2 = df2[df2['지역명'] == '청천동'].copy()
chungchun2['지역명']='청천2동'
df2 = pd.concat([df2, chungchun2], ignore_index=True)

huesong1 = df2[df2['지역명'] == '효성동'].copy()
huesong1['지역명']='효성1동'
df2 = pd.concat([df2, huesong1], ignore_index=True)

huesong2 = df2[df2['지역명'] == '효성동'].copy()
huesong2['지역명']='효성2동'
df2 = pd.concat([df2, huesong2], ignore_index=True)

yeonsu1= df2[df2['지역명'] == '연수동'].copy()
yeonsu1['지역명']='연수1동'
df2 = pd.concat([df2, yeonsu1], ignore_index=True)

yeonsu2= df2[df2['지역명'] == '연수동'].copy()
yeonsu2['지역명']='연수2동'
df2 = pd.concat([df2, yeonsu2], ignore_index=True)

yeonsu3= df2[df2['지역명'] == '연수동'].copy()
yeonsu3['지역명']='연수3동'
df2 = pd.concat([df2, yeonsu3], ignore_index=True)

seongyee1= df2[df2['지역명'] == '숭의동'].copy()
seongyee1['지역명']='숭의1,3동'
df2 = pd.concat([df2, seongyee1], ignore_index=True)

seongyee2= df2[df2['지역명'] == '숭의동'].copy()
seongyee2['지역명']='숭의2동'
df2 = pd.concat([df2, seongyee2], ignore_index=True)

seongyee3= df2[df2['지역명'] == '숭의동'].copy()
seongyee3['지역명']='숭의3동'
df2 = pd.concat([df2, seongyee3], ignore_index=True)

seongyee4= df2[df2['지역명'] == '숭의동'].copy()
seongyee4['지역명']='숭의4동'
df2 = pd.concat([df2, seongyee4], ignore_index=True)

seoknam1= df2[df2['지역명'] == '석남동'].copy()
seoknam1['지역명']='석남1동'
df2 = pd.concat([df2, seoknam1], ignore_index=True)

seoknam2= df2[df2['지역명'] == '석남동'].copy()
seoknam2['지역명']='석남2동'
df2 = pd.concat([df2, seoknam2], ignore_index=True)

seoknam3= df2[df2['지역명'] == '석남동'].copy()
seoknam3['지역명']='석남3동'
df2 = pd.concat([df2, seoknam3], ignore_index=True)

okruen1= df2[df2['지역명'] == '옥련동'].copy()
okruen1['지역명']='옥련1동'
df2 = pd.concat([df2, okruen1], ignore_index=True)

okruen2= df2[df2['지역명'] == '옥련동'].copy()
okruen2['지역명']='옥련2동'
df2 = pd.concat([df2, okruen2], ignore_index=True)

hawsu2= df2[df2['지역명'] == '화수동'].copy()
hawsu2['지역명']='화수2동'
df2 = pd.concat([df2, hawsu2], ignore_index=True)

seepjang1= df2[df2['지역명'] == '십정동'].copy()
seepjang1['지역명']='십정1동'
df2 = pd.concat([df2, seepjang1], ignore_index=True)

seepjang2= df2[df2['지역명'] == '십정동'].copy()
seepjang2['지역명']='십정2동'
df2 = pd.concat([df2, seepjang2], ignore_index=True)

In [9]:
chg1= df2[df2['지역명'] == '화수1.화평동'].copy()
chg1['지역명']='화수1,화평동'
df2 = pd.concat([df2, chg1], ignore_index=True)
df2 = df2.drop(df2[df2['지역명'] == '화수1.화평동'].index)

In [10]:
for dong in non_matching: 
    df2 = df2.drop(df2[df2['지역명'] == f'{dong}'].index)

In [11]:
unique_names_df = set(df['지역명'].unique())
unique_names_df2 = set(df2['지역명'].unique())

# df에는 있지만 df2에는 없는 고유한 값들을 찾음
unique_names_only_in_df = unique_names_df - unique_names_df2

# 찾은 값들 출력
print(unique_names_only_in_df)
print(len(unique_names_only_in_df))
miss_list=['산곡4동', '부평6동', '부평5동', '삼산2동', '부평4동', '부평2동', '산곡1동', '삼산1동', '율목동', '남촌도림동', '산곡3동', '영종1동', '부평3동', '부개1동', '산곡2동', '부개2동', '부개3동', '부평1동']

{'부개1동', '삼산1동', '산곡4동', '율목동', '부평2동', '영종1동', '부평1동', '부평6동', '산곡3동', '삼산2동', '산곡1동', '산곡2동', '부평5동', '부평4동', '남촌도림동', '부개3동', '부개2동', '부평3동'}
18

In [12]:
add_keward=pd.read_csv('add_keward.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'add_keward.csv'

In [21]:
file1=pd.read_csv('add_keward4.csv')
file2=pd.read_csv('add_keward2.csv')
file3=pd.read_csv('add_keward3.csv')

In [22]:
combined_df = pd.concat([file1, file2, file3], ignore_index=True)

In [23]:
combined_df = combined_df.rename(columns={'id': '지역명'})

In [24]:
combined_df

        지역명                                             review    keward
0     남촌도림동  빵종류 다양하고 주차넓고 커피도 맛있어요. 야외자리도 많아서 날씨 좋은날 오면 정말...   빵이 맛있어요
1     남촌도림동                             아이와 힐링하러왔어요 즐거운 시간이였어요    뷰가 좋아요
2     남촌도림동  오랜만에 왔는데 빵 종류도 더 다양해지고 좋아졌어요! 분위기도 좋고 빵이랑 커피 너...   빵이 맛있어요
3     남촌도림동  날씨가 좋아서 야외에서 음료랑 디저트 먹기 좋은 장\n소네요 가족모임후 여럿 왔는데...   빵이 맛있어요
4     남촌도림동  우연치않게 지나가다 들른 카페인데 커피도 빵도 맛\n있었고 분위기가 좋았던 곳이네요...   빵이 맛있어요
...     ...                                                ...       ...
8387    율목동  좌석도 엄청 편안해서 오래머물러도 좋은 곳 \n거기에 음료 종류도 다양한데 친구들이...  커피가 맛있어요
8388    율목동  지나가다가 커피 한잔 하기 딱 좋은 듯 \n비싸고 좋은 원두 사용하셔서 그런지 다른...  커피가 맛있어요
8389    율목동  카페 내부도 깔끔하고 커피 맛이며 디저트며 \n다 기분 좋게 만드네요 .. 처음 갔...      친절해요
8390    율목동   조용하고 깔끔한 카페\n거기에 에이드 맛까지 시원하고 탁 쏘니깐\n더 맛있게 먹었습니당  커피가 맛있어요
8391    율목동             무인카페라 편하고 밤늦은시간에도 맘껏 사먹을 수 있어서\n좋아요~^^      친절해요

[8392 rows x 3 columns]

In [18]:
from collections import Counter
combined_df = combined_df.groupby('지역명')['keward'].apply(lambda x: Counter(x)).reset_index()
combined_df

       지역명       level_1  keward
0    남촌도림동       빵이 맛있어요   143.0
1    남촌도림동        뷰가 좋아요    63.0
2    남촌도림동     인테리어가 멋져요    96.0
3    남촌도림동      커피가 맛있어요   495.0
4    남촌도림동   특별한 메뉴가 있어요    28.0
..     ...           ...     ...
267    율목동    메뉴 구성이 알차요     NaN
268    율목동  반려동물과 가기 좋아요     NaN
269    율목동   비싼 만큼 가치있어요     NaN
270    율목동       음악이 좋아요     NaN
271    율목동    아이와 가기 좋아요     NaN

[272 rows x 3 columns]

In [19]:
combined_df=combined_df.pivot(index='지역명',columns='level_1',values='keward')
combined_df

level_1,가성비가 좋아요,건강한 맛이에요,대화하기 좋아요,디저트가 맛있어요,매장이 넓어요,매장이 청결해요,메뉴 구성이 알차요,반려동물과 가기 좋아요,뷰가 좋아요,비싼 만큼 가치있어요,...,주차하기 편해요,집중하기 좋아요,차분한 분위기에요,친절해요,커피가 맛있어요,컨셉이 독특해요,특별한 메뉴가 있어요,포장이 깔끔해요,혼밥하기 좋아요,화장실이 깨끗해요
지역명,,,,,,,,,,,,,,,,,,,,,
남촌도림동,6.0,NaN,43.0,98.0,3.0,21.0,NaN,NaN,63.0,NaN,...,41.0,2.0,3.0,49.0,495.0,NaN,28.0,NaN,NaN,2.0
부개1동,10.0,3.0,3.0,125.0,1.0,11.0,NaN,NaN,1.0,NaN,...,NaN,4.0,NaN,51.0,46.0,NaN,18.0,1.0,NaN,NaN
부평5동,14.0,NaN,40.0,123.0,5.0,22.0,1.0,1.0,NaN,NaN,...,1.0,7.0,NaN,79.0,314.0,4.0,44.0,NaN,1.0,10.0
부평6동,14.0,NaN,40.0,299.0,5.0,24.0,1.0,1.0,NaN,NaN,...,NaN,7.0,NaN,90.0,320.0,4.0,54.0,NaN,1.0,10.0
산곡4동,29.0,29.0,30.0,218.0,5.0,45.0,3.0,1.0,4.0,1.0,...,5.0,18.0,1.0,101.0,302.0,NaN,54.0,NaN,NaN,2.0
삼산2동,15.0,NaN,34.0,323.0,1.0,46.0,NaN,NaN,8.0,2.0,...,4.0,10.0,1.0,149.0,331.0,2.0,69.0,NaN,NaN,6.0
영종1동,8.0,3.0,25.0,217.0,7.0,35.0,1.0,1.0,57.0,1.0,...,9.0,5.0,NaN,96.0,457.0,NaN,29.0,NaN,NaN,7.0
율목동,NaN,NaN,11.0,45.0,NaN,7.0,NaN,NaN,NaN,NaN,...,NaN,2.0,NaN,32.0,178.0,NaN,2.0,NaN,NaN,5.0

In [ ]:
df4=pd.read_csv('test2.csv')
df4.fillna(0,inplace=True)

In [ ]:
unique_names_df = set(df['지역명'].unique())
unique_names_df2 = set(df4['지역명'].unique())

# df에는 있지만 df2에는 없는 고유한 값들을 찾음
unique_names_only_in_df = unique_names_df2 - unique_names_df

# 찾은 값들 출력
print(unique_names_only_in_df)
print(len(unique_names_only_in_df))

In [ ]:
add_keward2.fillna(0,inplace=True)
add_keward2=add_keward2.astype(int)
add_keward2

In [ ]:
df2 = pd.concat([df2, add_keward2], ignore_index=True)

In [ ]:
df2.to_csv('test1.csv',index=False, encoding='utf-8-sig')

In [ ]:
df5 = pd.merge(df, df4, on='지역명')

In [ ]:
df5.to_csv('merge_cafedata_set.csv',index=False, encoding='utf-8-sig')